### ISSUE TITLE
About univariate dataset UCRArchive_2018

### ISSUE THREAD

**Issue by fengxijia** [yujingmarkjiang/Time_Series_Backdoor_Attack#2]
Hi, I noticed the code reads .tsv file instead of .ts file, whereas the UCRArchive_2018 dataset from the link you shared seems to only have .ts file instead of .tsv file. What should I do to read the dataset? Should I change all the .ts files to .tsv files, or change the read dataset code from .tsv to .ts? (The data inside .ts files have some headers, and there's less information about the .ts file. I only found one web using a customized function to read them. ) I would greatly appreciate your help with this. Thank you very much.

**Comment by yujingmarkjiang** [comment]
[archives.zip](https://github.com/yujingmarkjiang/Time_Series_Backdoor_Attack/files/12266250/archives.zip)

Please find the attached archive, which is processed and can be directly used.
